# Generated by Django 5.0.3 on 2024-04-10 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 4, 10)),
        ),
    ]
